
trigger:
  branches:
    include:
      - main
      - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  pythonVersion: '3.11'
  workingDirectory: '.'

stages:
- stage: Build
  displayName: 'Build Application'
  jobs:
  - job: BuildJob
    displayName: 'Build FastAPI Application'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'
      displayName: 'Use Python $(pythonVersion)'

    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: 'Install Python dependencies'
      workingDirectory: '$(workingDirectory)'

    - script: |
        # Initialize database
        python -c "
from app.database import engine
from app.models import *
from sqlmodel import SQLModel
SQLModel.metadata.create_all(engine)
        "
      displayName: 'Initialize Database'
      workingDirectory: '$(workingDirectory)'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(workingDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
        replaceExistingArchive: true
        excludePaths: |
          node_modules/**
          .git/**
          __pycache__/**
          *.pyc
          .env
      displayName: 'Archive application files'

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'drop'
      displayName: 'Publish build artifacts'

- stage: Deploy
  displayName: 'Deploy to Azure App Service'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployJob
    displayName: 'Deploy FastAPI Application'
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            inputs:
              azureSubscription: '$(AZURE_SERVICE_CONNECTION)'
              appType: 'webAppLinux'
              appName: '$(AZURE_APP_NAME)'
              package: '$(Pipeline.Workspace)/drop/app.zip'
              runtimeStack: 'PYTHON|3.11'
              startUpCommand: 'uvicorn app.main:app --host 0.0.0.0 --port 8000'
            displayName: 'Deploy to Azure App Service'

          - script: |
              echo "Application deployed successfully!"
              echo "Your FastAPI app should be available at https://$(AZURE_APP_NAME).azurewebsites.net"
            displayName: 'Deployment confirmation'
