# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - iom-d-we-datallmpoc-prompt-lib-01

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Ensure requirements.txt exists
        run: |
          # Use existing requirements.txt if it exists, otherwise generate from pyproject.toml
          if [ ! -f "requirements.txt" ]; then
            echo "Generating requirements.txt from pyproject.toml..."
            pip install toml
            python -c "
          import toml
          data = toml.load('pyproject.toml')
          deps = data['project']['dependencies']
          with open('requirements.txt', 'w') as f:
              for dep in deps:
                  f.write(dep + '\n')
          "
          else
            echo "Using existing requirements.txt"
          fi
          
          # Verify requirements.txt contains azure packages
          if ! grep -q "azure-storage-blob" requirements.txt; then
            echo "azure-storage-blob>=12.19.0" >> requirements.txt
          fi
          if ! grep -q "azure-core" requirements.txt; then
            echo "azure-core>=1.30.0" >> requirements.txt
          fi

      - name: Install dependencies
        run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !venv/
            !.git/
            !__pycache__/
            !*.pyc
            !.pytest_cache/
          retention-days: 30
            !.git/
            !__pycache__/
            !*.pyc
            !.pytest_cache/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'iom-d-we-datallmpoc-prompt-lib-01'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_5BF3B71B25AF441B8C3B893DC6954C68 }}
          startup-file: 'startup.sh'